### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by michael-ciniawsky** [postcss/postcss-loader#177]
## Roadmap

- [x] Drop `node =< v4`
- [x] Add `schema-utils` (Options Validation)
- [x] Update `loader-utils`
- [x] Update README.md
- [x] Refactor Tests (webpack && Jest)
- [x] Refactor `options.config = { path: 'path/to/config', ctx: {} }`
- [x] Expose `ctx = { file, options, env }`
- [x] Export Modules (CJS)
- [x] PostCSS v6.0.0

**webpack.config.js**
```js
{
  test: /\.css$/
  use: [ 
    { 
      loader: 'postcss-loader',
      options: { config: { path: 'path/to/postcss.config.js', ctx: {} }
    }
  ]
}
```

**postcss.config.js**
```js
module.exports = ({ file, options, env }) => ({
    parser: file.extname === '.sss' ? 'sugarss' : false,
    plugins: {
      'postcss-import': { root: file.dirname },
      'postcss-modules': options.modules ? {} : false
      'cssnano': env === 'production' ? { safe: true } : false
    }    
})
```

## Breaking Chances

- [x] Remove`ctx.webpack`
- [x] Remove Presets `options.pack`
- [x] Remove webpack Plugin Hook

cc @ai

**Comment by ai** [comment]
> Remove ctx.webpack (big && slow) in favour of ctx.file ?

Maybe. What other useful information could be in `loader`?

> Remove Presets/Packages options.pack ?

I afraid webpack 1 users :D. But `pack` is not so popular. We can ask them to migrate to `webpack` 2 or keep old version.

> Drop node v0.10/0.12?

Of course.

> Wait for PostCSS v6.0.0?

Good idea if we can wait about month (I am preparing for React London).

**Comment by michael-ciniawsky** [comment]
>Maybe. What other useful information could be in loader?

The only important I can think of atm is `loader.addDependency(file)` => `ctx.watch(file)/ctx.webpack.watch(file)` , but I will check what else we may have there 😛 

> I afraid webpack 1 users :D. But pack is not so popular. We can ask them to migrate to webpack 2 or keep old version.

I have no Twitter, but maybe a poll would be a good idea to see how popular the feature is, never seen it in the endless configs @extrac-text-webpack-plugin and the like, but who knows...

> Of course.

👍 

> Good idea if we can wait about month (I am preparing for React London).

Yep I also in favour to wait, no rush at all and if I have a month to get it working I will continue experimenting with 'removing' `css-loader` and get CSSModules working with `postcss-loader` ou-of-the-box e.g 

```js
// Last Loader e.g 'postcss-loader!sass-loader'
if (loader.loaderIndex >= 0) 
   // webpack 2 => ES2015 Module
   if (process.env.WEBPACK_VERSION === 2) {
      const module = `export default ${result.css}`
      return callback(null, module)
   }
   // webapck 1 => CJS Module
   const module = `module.exports = ${result.css}`
   return callback(null, module)
} else {
   // Next Loader => {String}
   return callback(null, result.css)
}
```

But experimental and only it works without headaches :D

**Comment by ai** [comment]
I added issue to bookmarks and will tweet about it on next week to collect more feedback.

Also we will need good step-by-step migration instructions.

**Comment by michael-ciniawsky** [comment]
@evilebottnawi I need to triage a few small things before actually ready and @ai needs to approve it then :), It's blocked by a few other things, while we can go with `module.exports` (CJS) for now, I need to test adding `css-base` from `css-loader` first (Module Deduplication), it's more complicated 😛

**Comment by ai** [comment]
@michael-ciniawsky maybe you should be a maintainer for this loader? Anyway you answered for most of issues. Rest work is simple and doesn't need too much time.

**Comment by evilebottnawi** [comment]
@ai @michael-ciniawsky i can help with this, besides, I am well acquainted with postcss and webpack :smile:

**Comment by ai** [comment]
Good idea too. Let's wait for @michael-ciniawsky answer and transfer maintaince 😊

**Comment by michael-ciniawsky** [comment]
@ai ? 🙃 I can take 'full' maintainance of this loader of course 😛 `npm owner add` or an npm organisation (`teams`) in case you want more 'control'.

@evilebottnawi Yeah sure welcome, Angular Commit Covention (`standard-version` => CHANGELOG.md), StandardJS >= v2.0.0 and we are up and running :)

**Comment by michael-ciniawsky** [comment]
@evilebottnawi I will recommend you for `css-loader` and co aswell, if you are interested we need all hands we can get :D

**Comment by michael-ciniawsky** [comment]
@ai `postcss-loader` => webpack-contrib?

**Comment by ai** [comment]
@michael-ciniawsky welcome on board (you can add @evilebottnawi as well).

I hope to release PostCSS 6 in next week.

**Comment by michael-ciniawsky** [comment]
No rush the webpack part will take longer :D

**Comment by evilebottnawi** [comment]
@michael-ciniawsky Today I thought and came to a conclusion: now `css-loader` is not `css` loader (some project don't use `css-modules`, but `css-loader` use their and it is weird and no way disable their, `module: false` it is not solution, because `postcss-modules-*` plugins anyway apply). 

In `postcss-loader` we want using their without `css-loader`, be right move all logic exclude `css-modules` from `css-loader`, also be right rename `css-loader` to `css-modules-loader` and remove all behavior not related to `css-modules` (imports, urls and etc). It is allow use `postcss-loader` for project don't use `css-modules`, if you need `css-modules`, just add `css-modules-loader` above `postcss-loader`. 

This would not only give a huge performance advantage, but also clearly divide the mixed logic, which causes the head to explode

**Comment by evilebottnawi** [comment]
@michael-ciniawsky Also after release `postcss-loader` it is should be named as `css-loader` :smile: (because it is veritable loader for css, without extra mixed logic as in `css-loader`).

**Comment by michael-ciniawsky** [comment]
@evilebottnawi Could you please drop my your e-mail so we can add you to the @webpack slack 😛?

**Comment by evilebottnawi** [comment]
@michael-ciniawsky sheo13666q@gmail.com :1st_place_medal:

**Comment by michael-ciniawsky** [comment]
You should got or get an invite soon :)
